server:
  port: 8090
spring:
  application:
    name: zipkinclient
  sleuth: # 帮助它监控的一个组件
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9090/  # 服务端的url地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
