server:
  port: 8050
spring:
  application:
    name: feignService
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  # 将IP注册
  instance:
    prefer-ip-address: true
feign:
  # 容错机制
  hystrix:
    enabled: true